name: disaster_aid
description: "A Flutter application for disaster aid coordination and management."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Map dependencies (moved from incorrect nesting)
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  
  # Firebase services
  firebase_core: ^2.27.2
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.9
  
  # UI components
  cupertino_icons: ^1.0.8
  getwidget: ^6.0.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  
  # State management
  provider: ^6.1.1
  
  # Location and maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  
  # Data persistence
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  uuid: ^4.2.1
  path: ^1.8.3
  intl: ^0.19.0
  url_launcher: ^6.2.2
  package_info_plus: ^4.2.0
  
  # Media
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  
  # Connectivity
  connectivity_plus: ^5.0.2
  http: ^1.1.2
  
  # Notifications
  flutter_local_notifications: ^16.2.0
  firebase_storage: 11.6.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  mockito: ^5.4.2
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:  # Fix this indentation (two spaces, not four)
    - assets/
    - assets/images/
    - assets/icons/